# Generated by Django 6.0 on 2026-04-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('final_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('shop_location', models.CharField(max_length=255)),
                ('delivery_option', models.CharField(choices=[('Free Delivery', 'Free Delivery'), ('Paid Delivery', 'Paid Delivery (By Customer)'), ('Shop Pickup', 'Picked from the shop')], default='Shop Pickup', max_length=20)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Skincare', 'Skincare'), ('Makeup', 'Makeup'), ('Haircare', 'Haircare'), ('Nailcare', 'Nailcare'), ('Wellness', 'Wellness'), ('Fragrance', 'Fragrance'), ('Tools & Accessories', 'Tools & Accessories')], max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
    ]
