# Generated by Django 5.2.7 on 2025-12-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Picked up', 'Picked up from the shop')], default='Delivered', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
