# Generated by Django 5.2.7 on 2025-12-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_delivery_status_product_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_status',
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_option',
            field=models.CharField(choices=[('Free Delivery', 'Free Delivery'), ('Paid Delivery', 'Paid Delivery (By Customer)'), ('Shop Pickup', 'Picked from the shop')], default='Shop Pickup', max_length=20),
        ),
    ]
