# Generated by Django 5.2.7 on 2025-12-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_delivery_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(choices=[('Skincare', 'Skincare'), ('Makeup', 'Makeup'), ('Haircare', 'Haircare'), ('Nailcare', 'Nailcare'), ('Wellness', 'Wellness'), ('Fragrance', 'Fragrance'), ('Tools & Accessories', 'Tools & Accessories')], max_length=100, unique=True),
        ),
    ]
