# Generated by Django 6.0 on 2026-04-05 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artistavailability',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to='artists.artist'),
        ),
        migrations.AlterUniqueTogether(
            name='artistavailability',
            unique_together={('artist', 'date', 'time')},
        ),
    ]
