# Generated by Django 5.2.7 on 2025-12-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistcategory',
            name='name',
            field=models.CharField(choices=[('Makeup', 'Makeup'), ('Hair', 'Hair'), ('Nails', 'Nails'), ('Spa & Massage', 'Spa & Massage'), ('Skincare', 'Skincare'), ('Henna', 'Henna'), ('Barber', 'Barber'), ('Lashes & Brows', 'Lashes & Brows')], max_length=100, unique=True),
        ),
    ]
