# Generated by Django 5.2.7 on 2025-12-20 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_populate_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistavailability',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to='artists.artist'),
        ),
    ]
