# Generated by Django 5.2.7 on 2025-12-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_alter_artistavailability_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='artist_profiles/'),
        ),
    ]
