# Generated by Django 5.2.7 on 2025-12-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('seller', 'Seller'), ('artist', 'Artist'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
